version: "3"

services:
  ha:
    container_name: ha
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - ./volumes/ha/config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    network_mode: host
    restart: unless-stopped
