services:
  ha:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: ha
    volumes:
      - ./volumes/ha/config:/config
    environment:
      - PGID=1000
      - PUID=1000
      - REVERSE_PROXY_IP_ADDRESS
      - TZ
    network_mode: host
    restart: unless-stopped
