version: "3"

# HomeKit device adoption notice:
# To discover new HomeKit devices, network_mode: host must be used. After pairing, it can be switched back to a driver: bridge network.
# Futhermore, any proxy configuration (/volumes/config/configuration.yaml proxy settings) must be disabled.
# Finally, multicast DNS is required.
# privileged: true *might* be required.
# https://github.com/linuxserver/docker-homeassistant#host-vs-bridge

# Reverse proxy configuration must be added to the home assistant configuration.yaml file:
# https://www.home-assistant.io/integrations/http#reverse-proxies

networks:
  frontend:
    driver: bridge
  ha-reverse-proxy-backend:
    external: true
  internet:
    driver: bridge

services:
# To update configs, use esphome repo locally with enc.
#  esphome:
#    container_name: esphome
#    image: ghcr.io/esphome/esphome
#    volumes:
#      - ./volumes/esphome-config:/config
#    environment:
#      ESPHOME_DASHBOARD_USE_PING: "true"
#    ports:
#      - 6052:6052/tcp
#    restart: unless-stopped

  ha:
    container_name: ha
    image: lscr.io/linuxserver/homeassistant:latest
    volumes:
      - ./volumes/ha/config:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      REVERSE_PROXY_IP_ADDRESS: ${REVERSE_PROXY_IP_ADDRESS}
    networks:
      - ha-reverse-proxy-backend
      - internet
    # ports:
    # Application WebUI, only use this if you are not using a reverse proxy
    #   - 8123:8123/tcp
    restart: unless-stopped

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: ha-nginx
    depends_on:
      - ha
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
    networks:
      frontend:
      ha-reverse-proxy-backend:
        ipv4_address: ${REVERSE_PROXY_IP_ADDRESS}
    volumes:
      - ./volumes/nginx/config:/config
    ports:
      - ${CLIENT_LAN_IP}:443:443
    restart: unless-stopped
